# ~modified~

CC = gcc
PD_PATH ?= /usr/
PD_INCLUDE_PATH = $(PD_PATH)/include
PYTHON_CFLAGS  := `python-config  --cflags`
PYTHON_LDFLAGS := `python-config  --ldflags`
EXTERNALS_EXT = pd_linux
MODULE_CFLAGS = -W -Wall -fPIC -shared -I$(PD_INCLUDE_PATH)

# ---------------------------------------------------------------------------- #
default: python.$(EXTERNALS_EXT)

# ---------------------------------------------------------------------------- #
python.$(EXTERNALS_EXT): src/pdpython.c
	$(CC) $(MODULE_CFLAGS) $^ -o $@ $(PYTHON_CFLAGS) $(PYTHON_LDFLAGS)
	chmod a-x python.$(EXTERNALS_EXT)

# ---------------------------------------------------------------------------- #
clean:
	-rm -r ./*.$(EXTERNALS_EXT)
